base_url = "https://pwnverse.github.io"
title = "Cyb0rG's Home"
build_search_index = true
generate_feed = true
minify_html = true

theme = "apollo"

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
use_cdn = false
theme = "toggle"

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
]

socials = [
    { name = "twitter", url = "https://twitter.com/_Cyb0rG", icon = "twitter" },
    { name = "github", url = "https://github.com/PwnVerse/", icon = "github" },
]

[extra.analytics]
enabled = true

[extra.analytics.goatcounter]
user = "Cyb0rG"

[extra.analytics.umami]
website_id = "74344cd8-1e87-4c38-8acd-f96049b8f07e"